version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: build/Dockerfile
    image: kenaz:local
    environment:
      - APP_CONFIG_FILE=/app/config/config.yaml
      - VAULT_PATH=/app/vault
      - SQLITE_PATH=/app/kenaz.db
    ports:
      - "8080:8080"
    volumes:
      - ./config:/app/config
      - ./vault:/app/vault
